# Java Gradle CircleCI 2.0 configuration file
# check: https://circleci.com/docs/2.0/language-java/
version: 2.1

# Defining a job to be called later in a workflow.
# check: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build-androidlibrary:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # check: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      # specify the version you desire here
      - image: cimg/android:2023.02

    # Add steps to the job
    # check: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Download depenencies
          command: ./gradlew androidDependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      # building project
      - run: 
          name: build project
          command: ./gradlew clean assemble

      # running tests
      - run:
          name: run tests
          command: ./gradlew test

workflows:
  build-androidibrary-workflow:
    jobs:
      - build-androidlibrary